### ISSUE TITLE
Share link not active

### ISSUE THREAD

**Issue by m0urs** [petitssuisses/piwigo-ShareAlbum#41]
I am using the theme "Stripped" http://piwigo.org/ext/extension_view.php?eid=471. However it seems that with that theme, the "Share" link provided by that plugin is not active. I can see in in the upper right of my screen but nothing happens if I am clicking on it. Is this a know issue? Is there a solution for it? Thanks.

**Comment by petitssuisses** [comment]
Hi. You're right, the plugin has some themes specificities (for the CSS and way the menu appears) and is tested with : Bootstrap Darkroom, Bootstrap default, clear, dark, elegant 
I will take a look with Stripped and let you know how or fix it.

**Comment by alentsch** [comment]
I experience the same with the "modus" theme, the "Share" link disappears. With the "Bootstrap Darkroom" theme however the "Share" link works.

**Comment by rorrison** [comment]
I'm having the same problem with "simple" and "elegant" themes (tested on Firefox and Chrome).

**Comment by williamkray** [comment]
with modus the new default theme of piwigo 2.10, i'm seeing something similar... the share link just simply isn't there. however, if i shrink the window down so that the various tool buttons contract to the three dots, the share link is there and useable, but without an icon. i'll try to post a few screenshots here:

private album navigation in a normal window:
![image](https://user-images.githubusercontent.com/8409433/66851782-3856a700-ef17-11e9-857a-3fdc18a91592.png)

if i shrink the window down significantly:
![image](https://user-images.githubusercontent.com/8409433/66851836-5ae8c000-ef17-11e9-9c7a-19658c02ddbe.png)

**Comment by bobribbon** [comment]
> if i shrink the window down so that the various tool buttons contract to the three dots, the share link is there and useable, but without an icon.

In my case, running 2.10.1, there is no link at all!

**Comment by petitssuisses** [comment]
Hi Gentlemen, the modus theme should be fixed with latest Github version. I will soon release a new version through Piwigo updates

**Comment by bobribbon** [comment]
> Hi Gentlemen, the modus theme should be fixed with latest Github version. I will soon release a new version through Piwigo updates
Thank you for your effort!

**Comment by petitssuisses** [comment]
@m0urs are you still using the stripped theme ? Because it's a nightmare to manage triggering actions.

**Comment by m0urs** [comment]
@petitssuisses No, I don't. I am using Bootstrap Darkroom in the meantime and everything is working fine for me. Thanks.

**Comment by petitssuisses** [comment]
Thanks. I'll code this issue and then definitely act that Stripped is not supported
