### ISSUE TITLE
When users use different share link, the get cookies related errors

### ISSUE THREAD

**Issue by freemann** [petitssuisses/piwigo-ShareAlbum#61]
When I renew or users use a different shared link, the get a lot of php/mysql errors.
![IMG-20201224-WA0003](https://user-images.githubusercontent.com/601053/103094100-b7a43800-45fc-11eb-9cd3-e244a08b3624.jpg)
When the user removes the site cookies, it all works again.

**Comment by petitssuisses** [comment]
Hi, this will be fixed in the next version hopefully.
It is because your "old" user (from the old shared link) is still in use (in session). In the next version, I purge existing sessions when a link is removed or renewed.
I assume that if you use a new private window when a link got renewed, it works ?
