### ISSUE TITLE
“You are not authorized to access the requested page”

### ISSUE THREAD

**Issue by xplosionmind** [petitssuisses/piwigo-ShareAlbum#71]
I do not understand what is going on.
I gave permissions for the album as in the screenshot below (`tommi` is the admin user)

![Screenshot 2021-03-06 at 9 43 00 AM](https://user-images.githubusercontent.com/42862428/110200891-60261200-7e60-11eb-86a0-864491d9ac7e.jpg)

But I get this when I use the ShareAlbum link:

![Screenshot 2021-03-06 at 9 40 24 AM](https://user-images.githubusercontent.com/42862428/110200898-6fa55b00-7e60-11eb-97de-76011be5fe26.jpg)

What did I do wrong?

Thank you very much!   
Best,   
T

**Comment by petitssuisses** [comment]
Hi
Please check that the album is visible to admin, in albums/properties - public vs private albums

**Comment by xplosionmind** [comment]
The album appears, and it is private.   
If I make it public, it becomes visible to everyone. How can I make it visible only for who has the link?

**Comment by petitssuisses** [comment]
What if you open the link in a private window ? (you not being logged in)

**Comment by xplosionmind** [comment]
The issue happens in the private window only (therefore without performing any login). On Sat, Mar 6, 2021 at 7:38 PM, Arnaud <notifications@github.com> wrote:  
What if you open the link in a private window ? (you not being logged in)

**Comment by xplosionmind** [comment]
@petitssuisses I forgot to mention that my Piwigo instance is not self-hosted. The only things I could do were trying to clear the cache etc.   
any ideas?

Thanks!

**Comment by tibey1** [comment]
I have to say I have the same problem. When I share an album, I only see pictures set to public. If I have no picture set to public (familly, friends, whatever), I have "You are not authorised to access the requested page".

**Comment by Wibias** [comment]
Yea still an Issue for me.

**Comment by Wibias** [comment]
Also adding the information that normal album sharing work for me. It doesnt work for Sub-Albums though.

**Comment by jwalck** [comment]
Since last update (not kept too good track of my versions though) on my self-hosted piwigo instance I can no longer use ShareAlbum. My previous shares still work but new shares which no matter how close I look appear identical in their setup do not, and get this error when I test in a private window. I'll dig through into the database and underlying data structure when I get the time to understand this issue. Currently using ShareAlbum 11.8 and the latest stable piwigo.

**Comment by erAck** [comment]
> I have to say I have the same problem. When I share an album, I only see pictures set to public. If I have no picture set to public (familly, friends, whatever), I have "You are not authorised to access the requested page".

That is correct behaviour. ShareAlbum does not grant a privacy level to the share user, and it should not (otherwise the share user would be able to view all non-public images of that level in any public album as well). All it does is granting access to an otherwise private album via group permissions.

**Comment by nicorikken** [comment]
I ran into this issue as well. I proposed a PR #89 to have at least some hint in the README.

**Comment by petitssuisses** [comment]
All, thanks for the proposals and #89. The extension page has been updated as well to mention this
